### PR TITLE
feat: add hertz_session

### PR DESCRIPTION
**Pull request by justlorain**
#### What type of PR is this?

feat: A new feature

#### What this PR does / why we need it (English/Chinese):

en: Supplement the example demo using hertz-contrib/sessions redis-based distributed Session and hertz-contrib/csrf
zh: 补充使用hertz-contrib/sessions扩展基于redis的分布式Session和hertz-contrib/csrf拓展的示例demo

#### Which issue(s) this PR fixes:

null

### CODE REVIEW

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
I think this project would be better if it had a front end and we could use IDL to define the api interface.

**Comment by justlorain** [comment]
> I think this project would be better if it had a front end and we could use IDL to define the api interface.

got, thx

**Comment by L2ncE** [comment]
Is it possible to add some comments to the key places?

**Comment by L2ncE** [comment]
Maybe it would be better to add a little bit introduction about redis-based distributed Session in the README.

**Review by li-jin-gou — APPROVED** [review]

**Comment by li-jin-gou** [comment]
LGTM

**Pull request merged**
