### PR TITLE
optimize: improve route demo

### PR DESCRIPTION
**Pull request by EduFriendChen**
#### What type of PR is this?

optimize

#### What this PR does / why we need it (English/Chinese):

en: improve route demo
zh: 完善了route的演示

### CODE REVIEW

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
lint need to fix

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
lint need to fix

**Comment by EduFriendChen** [comment]
> lint need to fix

I'm trying to fix it。

**Comment by Duslia** [comment]
ci check

**Comment by li-jin-gou** [comment]
LGTM

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
