### PR TITLE
add demo

### PR DESCRIPTION
**Pull request by 123kangning**
#### What type of PR is this?

request help (good first issue)

#### What this PR does / why we need it (English/Chinese):

使用 Hertz 和 Hz 为 hertz-examples/bizdemo 添加示例代码

#### Which issue(s) this PR fixes:	

#486

### CODE REVIEW

**Comment by 123kangning** [comment]
I have added the License header

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz/issues/486 and this demo looks a bit repetitive with https://github.com/cloudwego/hertz-examples/tree/main/hz

**Comment by 123kangning** [comment]
It looks like this, so is this issue redundant?Maybe my PR should be closed

**Comment by li-jin-gou** [comment]
> It looks like this, so is this issue redundant?Maybe my PR should be closed

Write a business demo code use Hertz and Hz such as student infomation manager system.

**Pull request closed without merging**
