### PR TITLE
chore(gomodule): upgrade kitex and kitex-contrib/obs-opentelemetry version

### PR DESCRIPTION
**Pull request by CoderPoet**
#### What type of PR is this?

chore: upgrade kitex and kitex-contrib/obs-opentelemetry version
#### What this PR does / why we need it (English/Chinese):

en: Solve the problem that high versions of Go cannot be compiled (https://github.com/cloudwego/kitex/issues/645)
zh: 修复高版本无法编译问题(https://github.com/cloudwego/kitex/issues/645)

### CODE REVIEW

**Comment by li-jin-gou** [comment]
need to solve conflict

**Review by li-jin-gou — APPROVED** [review]

**Comment by CoderPoet** [comment]
> need to solve conflict

done

**Comment by welkeyever** [comment]
Seems still have conflicts.

**Comment by CoderPoet** [comment]
> Seems still have conflicts.

done

**Review by Duslia — APPROVED** [review]

**Pull request merged**
